
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build -t gautam9611/nodeapp .
    - run: echo "${{DOCKERHUB_PASSWORD}}" | docker login -u ${{DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push gautam9611/nodeapp:latest
